sonar.projectKey=commons-lang-analysis
sonar.projectName=Apache Commons Lang
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=squ_7a3ed761dff2f525e6002fc3dffb99db48153a76